### ISSUE TITLE
The anchors open a new tab

### ISSUE THREAD

**Issue by pax0s** [ichpuchtli/awesome-rxjs#8]
Thanks for these resources but all the anchors unfortunately open a new tab which can be really annoying.

**Comment by ichpuchtli** [comment]
Doesn't for me. Thats weird.

**Comment by pax0s** [comment]
Sorry, my bad, not on the readme of the repo itself but rather on [https://devhub.io/repos/ichpuchtli-awesome-rxjs#getting-started](). I found this repo through this site but now that I think of it, it may be generated from the README markdown of the repo, so has nothing to do with you, I close this.
